"""create cart items table

Revision ID: a622235bfaf9
Revises: 2cd8c68c2c96
Create Date: 2026-06-04 08:16:30.876401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a622235bfaf9'
down_revision: Union[str, None] = '2cd8c68c2c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_at_add', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='check_quantity_min'),
    sa.CheckConstraint('user_id IS NOT NULL OR session_id IS NOT NULL', name='cart_identity'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cart_session_sku', 'cart_items', ['session_id', 'sku_id'], unique=True, postgresql_where=sa.text('session_id IS NOT NULL'))
    op.create_index('idx_cart_user_sku', 'cart_items', ['user_id', 'sku_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_index(op.f('ix_cart_items_session_id'), 'cart_items', ['session_id'], unique=False)
    op.create_index(op.f('ix_cart_items_sku_id'), 'cart_items', ['sku_id'], unique=False)
    op.create_index(op.f('ix_cart_items_user_id'), 'cart_items', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_items_user_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_sku_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_session_id'), table_name='cart_items')
    op.drop_index('idx_cart_user_sku', table_name='cart_items', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('idx_cart_session_sku', table_name='cart_items', postgresql_where=sa.text('session_id IS NOT NULL'))
    op.drop_table('cart_items')
    # ### end Alembic commands ###
