"""add_b2b_fulfilled_to_orders

Revision ID: d0c6e0675dc8
Revises: 01c94d0a6b1f
Create Date: 2026-06-07 13:25:49.278227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c6e0675dc8'
down_revision: Union[str, None] = '01c94d0a6b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('b2b_fulfilled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'b2b_fulfilled')
    # ### end Alembic commands ###
