"""add_unavailable_reason_and_event_idempotency

Revision ID: 596ccf526756
Revises: d52bcddc3729
Create Date: 2026-06-07 12:18:19.612033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596ccf526756'
down_revision: Union[str, None] = 'd52bcddc3729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_idempotency_keys',
    sa.Column('key', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.add_column('cart_items', sa.Column('unavailable_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'unavailable_reason')
    op.drop_table('event_idempotency_keys')
    # ### end Alembic commands ###
